name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
