name: Release Package

on:
  release:
    types:
      - published

jobs:
  release:
    environment: nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: pack and push
        env:
          nuget_key: ${{ secrets.NUGETAPIKEY }}
        run: |
          Version=${GITHUB_REF:10}
          ./pack.sh ${Version:1}
          dotnet nuget push ./artifacts/*.* -s https://api.nuget.org/v3/index.json -k $nuget_key --skip-duplicate
